import React, { useState, useEffect, useRef } from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Card, CardContent } from '@/components/ui/card';
import { 
  Loader2, 
  Plus, 
  X
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { useRole } from '@/contexts/RoleContext';
import { employeeApi, branchesApi, Gender as GenderEnum, MaritalStatus as MaritalStatusEnum, EmploymentType as EmploymentTypeEnum } from '@/lib/api';
import type { Department, Position, CreateEmployeeRequest, UpdateEmployeeRequest, Gender, MaritalStatus, EmploymentType, Branch } from '@/lib/api';

interface EmployeeOnboardFormProps {
  isOpen: boolean;
  onClose: () => void;
  onSubmit: (employeeData: any) => void;
  editingEmployee?: any | null;
}

interface EmployeeFormData {
  // Personal Information
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  dateOfBirth: string;
  gender: string;
  maritalStatus: string;
  unit: string;
  
  // Address Information
  address: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  
  
  // Employment Information
  employeeId: string;
  department: string;
  position: string;
  joiningDate: string;
  contractType: string;
  terminated: string;
}

export const EmployeeOnboardForm = ({
  isOpen,
  onClose,
  onSubmit,
  editingEmployee,
}: EmployeeOnboardFormProps) => {
  const { currentUser } = useRole();
  // Employee ID is now generated by the API, not the frontend
  // Removed sequenceCounterRef, sanitizeUnit, and deriveUnitCode as they're no longer needed

  const buildInitialFormData = (unit = ''): EmployeeFormData => ({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    dateOfBirth: '',
    gender: '',
    maritalStatus: '',
    unit,
    address: '',
    city: '',
    state: '',
    postalCode: '',
    country: '',
    employeeId: '',
    department: '',
    position: '',
    joiningDate: '',
    contractType: '',
    terminated: 'no',
  });

  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errors, setErrors] = useState<Record<string, string>>({});
  const [customDepartment, setCustomDepartment] = useState('');
  const [showCustomDepartmentInput, setShowCustomDepartmentInput] = useState(false);
  const [customPosition, setCustomPosition] = useState('');
  const [showCustomPositionInput, setShowCustomPositionInput] = useState(false);
  const [formData, setFormData] = useState<EmployeeFormData>(() => buildInitialFormData());

  // API data states
  const [departments, setDepartments] = useState<Department[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [branches, setBranches] = useState<Branch[]>([]);
  const [isLoadingDepartments, setIsLoadingDepartments] = useState(false);
  const [isLoadingPositions, setIsLoadingPositions] = useState(false);
  const [isLoadingBranches, setIsLoadingBranches] = useState(false);
  const [isLoadingEmployee, setIsLoadingEmployee] = useState(false);
  const [apiEmployee, setApiEmployee] = useState<any>(null);

  // Get contract types from enum (excluding TERMINATED as it's not for new employees)
  const contractTypes = Object.values(EmploymentTypeEnum)
    .filter(type => type !== EmploymentTypeEnum.TERMINATED)
    .map(type => ({
      value: type,
      label: type.charAt(0).toUpperCase() + type.slice(1)
    }));

  // Get genders from enum
  const genders = Object.values(GenderEnum).map(gender => ({
    value: gender,
    label: gender.charAt(0).toUpperCase() + gender.slice(1)
  }));

  // Get marital statuses from enum
  const maritalStatuses = Object.values(MaritalStatusEnum).map(status => ({
    value: status,
    label: status.charAt(0).toUpperCase() + status.slice(1)
  }));

  // Fetch employee data from API when editing
  useEffect(() => {
    const fetchEmployeeData = async () => {
      if (editingEmployee?.id && isOpen) {
        setIsLoadingEmployee(true);
        try {
          const employeeId = parseInt(editingEmployee.id);
          if (!isNaN(employeeId)) {
            const employee = await employeeApi.getEmployeeById(employeeId);
            setApiEmployee(employee);
          }
        } catch (error) {
          console.error('Error fetching employee data:', error);
          toast({
            title: 'Error',
            description: 'Failed to load employee data. Using cached data.',
            variant: 'destructive',
          });
          setApiEmployee(null);
        } finally {
          setIsLoadingEmployee(false);
        }
      } else {
        setApiEmployee(null);
      }
    };

    fetchEmployeeData();
  }, [editingEmployee?.id, isOpen]);

  // Track if form has been initialized to prevent resetting on department/position updates
  const formInitializedRef = useRef(false);
  const previousIsOpenRef = useRef(false);
  const previousEditingEmployeeIdRef = useRef<string | null>(null);

  // Prefill form data when editing (only on initial open, not when departments/positions change)
  useEffect(() => {
    // Reset initialization flag when dialog closes
    if (!isOpen) {
      formInitializedRef.current = false;
      previousIsOpenRef.current = false;
      previousEditingEmployeeIdRef.current = null;
      return;
    }

    // Check if we're editing a different employee - if so, reset initialization
    const currentEditingId = editingEmployee?.id || null;
    if (currentEditingId !== previousEditingEmployeeIdRef.current) {
      formInitializedRef.current = false;
      previousEditingEmployeeIdRef.current = currentEditingId;
    }

    // If we're editing and still loading employee data, wait
    if (editingEmployee && isLoadingEmployee) {
      console.log('Waiting for employee data to load...');
      return;
    }

    // If we're editing, wait for all dropdown data to load AND be populated
    // We need the data to match employee's department/position/branch
    if (editingEmployee) {
      const stillLoading = isLoadingBranches || isLoadingDepartments || isLoadingPositions;
      const dataNotReady = branches.length === 0 || departments.length === 0 || positions.length === 0;
      
      if (stillLoading || dataNotReady) {
        console.log('Waiting for dropdown data to load and populate...', {
          isLoadingBranches,
          isLoadingDepartments,
          isLoadingPositions,
          branchesCount: branches.length,
          departmentsCount: departments.length,
          positionsCount: positions.length,
        });
        return;
      }
    }

    // Only initialize form data when dialog first opens or when editing a different employee
    const isFirstOpen = !previousIsOpenRef.current && isOpen;
    previousIsOpenRef.current = isOpen;

    if (!isFirstOpen && formInitializedRef.current && currentEditingId === previousEditingEmployeeIdRef.current) {
      // Form already initialized for this employee, don't reset it
      return;
    }

    // Use API employee data if available, otherwise fall back to editingEmployee
    const employeeData = apiEmployee || editingEmployee;
    
    console.log('Form initialization check:', {
      isOpen,
      isFirstOpen,
      hasApiEmployee: !!apiEmployee,
      hasEditingEmployee: !!editingEmployee,
      isLoadingEmployee,
      isLoadingBranches,
      isLoadingDepartments,
      isLoadingPositions,
      branchesCount: branches.length,
      departmentsCount: departments.length,
      positionsCount: positions.length,
      employeeData: !!employeeData,
    });
    
    if (employeeData && isOpen) {
      // Use API employee structure if available
      // For unit, find the matching branch from the branches array to ensure exact match
      let unit = '';
      if (apiEmployee?.branch?.name) {
        // Try to find exact match in branches array
        const matchingBranch = branches.find(b => b.name === apiEmployee.branch?.name);
        unit = matchingBranch?.name || apiEmployee.branch.name;
      } else if (editingEmployee?.unit) {
        // Try to find exact match in branches array
        const matchingBranch = branches.find(b => b.name === editingEmployee.unit);
        unit = matchingBranch?.name || editingEmployee.unit;
      }
      
      const employeeDepartment = apiEmployee 
        ? (apiEmployee.department?.name || '')
        : (editingEmployee?.department || '');
      const employeePosition = apiEmployee 
        ? (apiEmployee.position?.name || '')
        : (editingEmployee?.position || '');
      
      // Check if department exists in the API list (compare by name)
      const departmentExists = employeeDepartment && departments.length > 0 && 
        departments.some(dept => dept.name === employeeDepartment);
      // Check if position exists in the API list (compare by name)
      const positionExists = employeePosition && positions.length > 0 && 
        positions.some(pos => pos.name === employeePosition);
      
      console.log('Setting form data with:', {
        unit,
        employeeDepartment,
        employeePosition,
        departmentExists,
        positionExists,
        branchesAvailable: branches.length,
        departmentsAvailable: departments.length,
        positionsAvailable: positions.length,
      });

      setFormData({
        firstName: apiEmployee?.firstName || editingEmployee?.firstName || '',
        lastName: apiEmployee?.lastName || editingEmployee?.lastName || '',
        email: apiEmployee?.email || editingEmployee?.email || '',
        phone: apiEmployee?.phoneNumber || editingEmployee?.phone || '',
        dateOfBirth: apiEmployee?.dateOfBirth || editingEmployee?.dateOfBirth || '',
        gender: apiEmployee?.gender || editingEmployee?.gender || '',
        maritalStatus: apiEmployee?.maritalStatus || editingEmployee?.maritalStatus || '',
        unit,
        address: apiEmployee?.address || editingEmployee?.address || '',
        city: apiEmployee?.city || editingEmployee?.city || '',
        state: apiEmployee?.state || editingEmployee?.state || '',
        postalCode: apiEmployee?.postalCode || editingEmployee?.postalCode || '',
        country: apiEmployee?.country || editingEmployee?.country || '',
        employeeId: apiEmployee?.employeeId || editingEmployee?.employeeId || '',
        // If department/position exists in API list, use it. Otherwise, it's custom and show input
        department: departmentExists ? employeeDepartment : (employeeDepartment ? 'Add Department' : ''),
        position: positionExists ? employeePosition : (employeePosition ? 'Add Position' : ''),
        joiningDate: apiEmployee?.joiningDate || editingEmployee?.joiningDate || '',
        // If employmentType is 'terminated', set terminated to 'yes' and preserve original contractType
        // Otherwise, use the employmentType as contractType
        contractType: (apiEmployee?.employmentType === EmploymentTypeEnum.TERMINATED || editingEmployee?.contractType === EmploymentTypeEnum.TERMINATED)
          ? (editingEmployee?.contractType || 'permanent') // Preserve original contract type if available
          : (apiEmployee?.employmentType || editingEmployee?.contractType || ''),
        terminated: (apiEmployee?.employmentType === EmploymentTypeEnum.TERMINATED || editingEmployee?.contractType === EmploymentTypeEnum.TERMINATED)
          ? 'yes'
          : (editingEmployee?.terminated ?? 'no'),
      });
      
      // Set custom department and position if they don't exist in API list
      if (employeeDepartment && !departmentExists) {
        setCustomDepartment(employeeDepartment);
        setShowCustomDepartmentInput(true);
      } else {
        setCustomDepartment('');
        setShowCustomDepartmentInput(false);
      }
      
      if (employeePosition && !positionExists) {
        setCustomPosition(employeePosition);
        setShowCustomPositionInput(true);
      } else {
        setCustomPosition('');
        setShowCustomPositionInput(false);
      }
      
      formInitializedRef.current = true;
      console.log('Form prefilled with employee data:', employeeData);
      console.log('Form data set:', {
        unit,
        department: departmentExists ? employeeDepartment : (employeeDepartment ? 'Add Department' : ''),
        position: positionExists ? employeePosition : (employeePosition ? 'Add Position' : ''),
      });
    } else if (!employeeData && isOpen && !editingEmployee && isFirstOpen) {
      // Only reset form on first open when creating new employee
      setFormData(buildInitialFormData());
      setCustomDepartment('');
      setShowCustomDepartmentInput(false);
      setCustomPosition('');
      setShowCustomPositionInput(false);
      formInitializedRef.current = true;
      console.log('Form initialized for new employee');
    }
  }, [apiEmployee, editingEmployee, isOpen, isLoadingEmployee, isLoadingBranches, isLoadingDepartments, isLoadingPositions, departments, positions, branches]);

  // Fetch departments, positions, and branches from API
  useEffect(() => {
    const fetchBranches = async () => {
      if (!isOpen) return;
      
      setIsLoadingBranches(true);
      try {
        const storedUser = localStorage.getItem('user');
        let companyId = 1;
        if (storedUser) {
          try {
            const parsed = JSON.parse(storedUser);
            companyId = parsed?.company?.id || parsed?.branch?.company?.id || 1;
          } catch {
            companyId = 1;
          }
        }
        
        const response = await branchesApi.getByCompanyId(companyId, {
          page: 1,
          limit: 100,
        });
        setBranches(response.data);
      } catch (error) {
        console.error('Error fetching branches:', error);
        toast({
          title: 'Error',
          description: 'Failed to load branches. Please try again.',
          variant: 'destructive',
        });
      } finally {
        setIsLoadingBranches(false);
      }
    };

    const fetchDepartments = async () => {
      if (!isOpen) return;
      
      setIsLoadingDepartments(true);
      try {
        const storedUser = localStorage.getItem('user');
        let companyId = 1;
        if (storedUser) {
          try {
            const parsed = JSON.parse(storedUser);
            companyId = parsed?.company?.id || parsed?.branch?.company?.id || 1;
          } catch {
            companyId = 1;
          }
        }
        const response = await employeeApi.getAllDepartments({
          companyId,
          page: 1,
          limit: 100,
        });
        setDepartments(response.data);
      } catch (error) {
        console.error('Error fetching departments:', error);
        toast({
          title: 'Error',
          description: 'Failed to load departments. Please try again.',
          variant: 'destructive',
        });
      } finally {
        setIsLoadingDepartments(false);
      }
    };

    const fetchPositions = async () => {
      if (!isOpen) return;
      
      setIsLoadingPositions(true);
      try {
        const storedUser = localStorage.getItem('user');
        let companyId = 1;
        if (storedUser) {
          try {
            const parsed = JSON.parse(storedUser);
            companyId = parsed?.company?.id || parsed?.branch?.company?.id || 1;
          } catch {
            companyId = 1;
          }
        }
        const response = await employeeApi.getAllPositions({
          companyId,
          page: 1,
          limit: 100,
        });
        setPositions(response.data);
      } catch (error) {
        console.error('Error fetching positions:', error);
        toast({
          title: 'Error',
          description: 'Failed to load positions. Please try again.',
          variant: 'destructive',
        });
      } finally {
        setIsLoadingPositions(false);
      }
    };

    if (isOpen) {
      fetchBranches();
      fetchDepartments();
      fetchPositions();
    }
  }, [isOpen, currentUser]);

  const handleInputChange = (field: string, value: string) => {
    setFormData((prev) => ({ ...prev, [field]: value }));
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: '' }));
    }
  };

  const handleSelectChange = (field: string, value: string) => {
    setFormData((prev) => {
      // For unit, keep the actual branch name (not sanitized) to match dropdown options
      // Only sanitize when generating employee ID
      const nextValue = value;
      const nextState = { ...prev, [field]: nextValue };

      if (field === 'unit' && !editingEmployee) {
        // Sanitize only for employee ID generation, but keep original value in formData
        // Employee ID is generated by API, not frontend
        // nextState.employeeId = generateEmployeeId(value); // Removed - API will generate
      }

      return nextState;
    });
    if (errors[field]) {
      setErrors((prev) => ({ ...prev, [field]: '' }));
    }
    
    // Handle custom department
    if (field === 'department' && value === 'Add Department') {
      setShowCustomDepartmentInput(true);
      setCustomDepartment('');
    } else if (field === 'department' && value !== 'Add Department') {
      setShowCustomDepartmentInput(false);
      setCustomDepartment('');
    }
    
    // Handle custom position
    if (field === 'position' && value === 'Add Position') {
      setShowCustomPositionInput(true);
      setCustomPosition('');
    } else if (field === 'position' && value !== 'Add Position') {
      setShowCustomPositionInput(false);
      setCustomPosition('');
    }
  };

  const handleAddDepartment = async () => {
    if (!customDepartment.trim()) {
      setErrors((prev) => ({ ...prev, customDepartment: 'Department name is required' }));
      return;
    }

    // Check if department already exists
    const departmentExists = departments.some(d => d.name.toLowerCase() === customDepartment.trim().toLowerCase());
    if (departmentExists) {
      setErrors((prev) => ({ ...prev, customDepartment: 'Department already exists' }));
      return;
    }

    setIsLoadingDepartments(true);
    try {
      // Get company ID
      const storedUser = localStorage.getItem('user');
      let companyId = 1;
      if (storedUser) {
        try {
          const parsed = JSON.parse(storedUser);
          companyId = parsed?.company?.id || parsed?.branch?.company?.id || 1;
        } catch {
          companyId = 1;
        }
      }

      // Create department via API
      const newDepartment = await employeeApi.createDepartment({
        name: customDepartment.trim(),
        description: `Custom department: ${customDepartment.trim()}`,
        companyId,
      });

      // Refresh departments list
      const response = await employeeApi.getAllDepartments({
        companyId,
        page: 1,
        limit: 100,
      });
      setDepartments(response.data);

      // Set the newly created department as selected
      setFormData((prev) => ({ ...prev, department: newDepartment.name }));
      setShowCustomDepartmentInput(false);
      setCustomDepartment('');
      setErrors((prev) => ({ ...prev, customDepartment: '' }));

      toast({
        title: 'Success',
        description: `Department "${newDepartment.name}" created successfully`,
      });
    } catch (error: any) {
      console.error('Error creating department:', error);
      toast({
        title: 'Error',
        description: error?.response?.data?.message || 'Failed to create department. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsLoadingDepartments(false);
    }
  };

  const handleAddPosition = async () => {
    if (!customPosition.trim()) {
      setErrors((prev) => ({ ...prev, customPosition: 'Position name is required' }));
      return;
    }

    // Check if position already exists
    const positionExists = positions.some(p => p.name.toLowerCase() === customPosition.trim().toLowerCase());
    if (positionExists) {
      setErrors((prev) => ({ ...prev, customPosition: 'Position already exists' }));
      return;
    }

    setIsLoadingPositions(true);
    try {
      // Get company ID
      const storedUser = localStorage.getItem('user');
      let companyId = 1;
      if (storedUser) {
        try {
          const parsed = JSON.parse(storedUser);
          companyId = parsed?.company?.id || parsed?.branch?.company?.id || 1;
        } catch {
          companyId = 1;
        }
      }

      // Create position via API
      const newPosition = await employeeApi.createPosition({
        name: customPosition.trim(),
        description: `Position: ${customPosition.trim()}`,
        companyId,
      });

      // Refresh positions list
      const response = await employeeApi.getAllPositions({
        companyId,
        page: 1,
        limit: 100,
      });
      setPositions(response.data);

      // Set the newly created position as selected
      setFormData((prev) => ({ ...prev, position: newPosition.name }));
      setShowCustomPositionInput(false);
      setCustomPosition('');
      setErrors((prev) => ({ ...prev, customPosition: '' }));

      toast({
        title: 'Success',
        description: `Position "${newPosition.name}" created successfully`,
      });
    } catch (error: any) {
      console.error('Error creating position:', error);
      toast({
        title: 'Error',
        description: error?.response?.data?.message || 'Failed to create position. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsLoadingPositions(false);
    }
  };


  const validateForm = () => {
    const newErrors: Record<string, string> = {};

    // Required field validations - only First Name, Last Name, Phone Number, and Factory Location
    if (!formData.firstName.trim()) newErrors.firstName = 'First name is required';
    if (!formData.lastName.trim()) newErrors.lastName = 'Last name is required';
    if (!formData.phone.trim()) newErrors.phone = 'Phone number is required';
    if (!formData.unit.trim()) newErrors.unit = 'Factory location is required';
    
    // Custom department/position validation (only if user is adding new ones)
    if (formData.department === 'Add Department' && !customDepartment.trim()) newErrors.customDepartment = 'Department name is required';
    if (formData.position === 'Add Position' && !customPosition.trim()) newErrors.customPosition = 'Position name is required';

    // Email validation (optional field, but validate format if provided)
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (formData.email && !emailRegex.test(formData.email)) {
      newErrors.email = 'Please enter a valid email address';
    }

    // Phone validation
    const phoneRegex = /^[\+]?[1-9][\d]{0,15}$/;
    if (formData.phone && !phoneRegex.test(formData.phone.replace(/\s/g, ''))) {
      newErrors.phone = 'Please enter a valid phone number';
    }

    return newErrors;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    const validationErrors = validateForm();
    if (Object.keys(validationErrors).length > 0) {
      setErrors(validationErrors);
      toast({
        title: 'Validation Error',
        description: 'Please fill in all required fields correctly.',
        variant: 'destructive',
      });
      return;
    }

    setIsSubmitting(true);

    try {
      if (!currentUser?.branch?.id) {
        throw new Error('Branch information is required');
      }

      // Get company ID from stored user data
      const storedUser = localStorage.getItem('user');
      let companyId = 1;
      if (storedUser) {
        try {
          const parsed = JSON.parse(storedUser);
          companyId = parsed?.company?.id || parsed?.branch?.company?.id || 1;
        } catch {
          companyId = 1;
        }
      }
      
      // Find the selected branch by name
      const selectedBranch = branches.find(b => b.name === formData.unit);
      if (!selectedBranch) {
        throw new Error('Please select a valid branch/unit');
      }
      const branchId = selectedBranch.id;

      // Handle department - optional field
      let departmentId: number | undefined;
      if (formData.department && formData.department.trim()) {
        if (formData.department === 'Add Department' && customDepartment.trim()) {
          const newDepartment = await employeeApi.createDepartment({
            name: customDepartment.trim(),
            description: `Custom department: ${customDepartment.trim()}`,
            companyId,
          });
          departmentId = newDepartment.id;
        } else if (formData.department !== 'Add Department') {
          // Find department by name
          const department = departments.find(d => d.name === formData.department);
          if (department) {
            departmentId = department.id;
          }
        }
      }

      // Handle position - optional field
      let positionId: number | undefined;
      if (formData.position && formData.position.trim()) {
        if (formData.position === 'Add Position' && customPosition.trim()) {
          const newPosition = await employeeApi.createPosition({
            name: customPosition.trim(),
            description: `Position: ${customPosition.trim()}`,
            companyId,
          });
          positionId = newPosition.id;
        } else if (formData.position !== 'Add Position') {
          const position = positions.find(p => p.name === formData.position);
          if (position) {
            positionId = position.id;
          }
        }
      }

      // Determine employment type: if terminated is 'yes', use 'terminated', otherwise use contractType
      const employmentType = formData.terminated === 'yes' 
        ? EmploymentTypeEnum.TERMINATED 
        : (formData.contractType as EmploymentType);

      // Map form data to API format
      const employeeData: any = {
        firstName: formData.firstName.trim(),
        lastName: formData.lastName.trim(),
        phoneNumber: formData.phone.trim(),
        companyId,
        branchId,
      };

      // Add optional fields only if they have values
      if (formData.email.trim()) {
        employeeData.email = formData.email.trim();
      }
      if (formData.dateOfBirth) {
        employeeData.dateOfBirth = formData.dateOfBirth;
      }
      if (formData.gender) {
        employeeData.gender = formData.gender as Gender;
      }
      if (formData.maritalStatus) {
        employeeData.maritalStatus = formData.maritalStatus as MaritalStatus;
      }
      if (formData.address.trim()) {
        employeeData.address = formData.address.trim();
      }
      if (formData.city.trim()) {
        employeeData.city = formData.city.trim();
      }
      if (formData.state.trim()) {
        employeeData.state = formData.state.trim();
      }
      if (formData.postalCode.trim()) {
        employeeData.postalCode = formData.postalCode.trim();
      }
      if (formData.country.trim()) {
        employeeData.country = formData.country.trim();
      }
      if (formData.joiningDate) {
        employeeData.joiningDate = formData.joiningDate;
      }
      if (employmentType) {
        employeeData.employmentType = employmentType;
      }

      // Only include departmentId and positionId if they are provided (optional fields)
      if (departmentId !== undefined) {
        employeeData.departmentId = departmentId;
      }
      if (positionId !== undefined) {
        employeeData.positionId = positionId;
      }

      if (editingEmployee || apiEmployee) {
        // Update existing employee - use API employee ID if available, otherwise use editingEmployee id
        const employeeId = apiEmployee?.id || parseInt(editingEmployee?.id || '0');
        if (isNaN(employeeId) || employeeId === 0) {
          throw new Error('Invalid employee ID');
        }
        await employeeApi.updateEmployee(employeeId, employeeData as UpdateEmployeeRequest);
      toast({
        title: 'Success',
          description: 'Employee updated successfully.',
        });
      } else {
        // Create new employee - API will generate employeeId
        const newEmployee = await employeeApi.createEmployee(employeeData as CreateEmployeeRequest);
        toast({
          title: 'Success',
          description: `Employee created successfully. Employee ID: ${newEmployee.employeeId || 'Assigned by system'}`,
        });
      }

      // Reset form
      setFormData(buildInitialFormData());
      setErrors({});
      setCustomDepartment('');
      setShowCustomDepartmentInput(false);
      setCustomPosition('');
      setShowCustomPositionInput(false);
      onSubmit(employeeData as any);
      onClose();
    } catch (error: any) {
      console.error('Error submitting employee form:', error);
      toast({
        title: 'Error',
        description: error?.message || 'Failed to submit employee onboarding form. Please try again.',
        variant: 'destructive',
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClose = () => {
    setFormData(buildInitialFormData());
    setErrors({});
    setCustomDepartment('');
    setShowCustomDepartmentInput(false);
    setCustomPosition('');
    setShowCustomPositionInput(false);
    setApiEmployee(null);
    setIsLoadingEmployee(false);
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className='max-w-6xl max-h-[90vh] overflow-y-auto'>
        <DialogHeader className='pb-2'>
          <DialogTitle className='flex items-center gap-2 text-lg'>
            <div className='w-8 h-8 bg-primary/10 rounded-lg flex items-center justify-center'>
              <Plus className='w-4 h-4 text-primary' />
            </div>
            {editingEmployee ? 'Edit Employee Details' : 'Employee Onboarding Form'}
          </DialogTitle>
        </DialogHeader>

        <form onSubmit={handleSubmit} className='space-y-3'>
          <Card className='border-0 shadow-sm'>
            <CardContent className='space-y-3'>
              {/* Personal Information */}
              <div className='space-y-2'>
                <h4 className='text-xs font-medium text-muted-foreground border-b pb-1'>
                  Personal Information
                </h4>

                <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4'>
                  <div className='space-y-1'>
                    <Label htmlFor='firstName' className='text-xs font-medium'>
                      First Name *
                    </Label>
                    <Input
                      id='firstName'
                      placeholder='Enter first name'
                      value={formData.firstName}
                      onChange={(e) => handleInputChange('firstName', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                    {errors.firstName && (
                      <p className='text-destructive text-xs mt-1'>{errors.firstName}</p>
                    )}
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='lastName' className='text-xs font-medium'>
                      Last Name *
                    </Label>
                    <Input
                      id='lastName'
                      placeholder='Enter last name'
                      value={formData.lastName}
                      onChange={(e) => handleInputChange('lastName', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                    {errors.lastName && (
                      <p className='text-destructive text-xs mt-1'>{errors.lastName}</p>
                    )}
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='phone' className='text-xs font-medium'>
                      Phone Number *
                    </Label>
                    <Input
                      id='phone'
                      type='tel'
                      placeholder='Enter phone number'
                      value={formData.phone}
                      onChange={(e) => handleInputChange('phone', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                    {errors.phone && (
                      <p className='text-destructive text-xs mt-1'>{errors.phone}</p>
                    )}
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='unit' className='text-xs font-medium'>
                    Factory Location*
                    </Label>
                    <Select
                      value={formData.unit}
                      onValueChange={(value) => handleSelectChange('unit', value)}
                    >
                      <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200 text-left'>
                        <SelectValue placeholder='Select unit' className='text-left' />
                      </SelectTrigger>
                      <SelectContent>
                        {isLoadingBranches ? (
                          <SelectItem value="loading" disabled>
                            Loading branches...
                          </SelectItem>
                        ) : (
                          branches.map((branch) => (
                            <SelectItem key={branch.id} value={branch.name}>
                              {branch.name} - {branch.location}
                            </SelectItem>
                          ))
                        )}
                      </SelectContent>
                    </Select>
                    {errors.unit && (
                      <p className='text-destructive text-xs mt-1'>{errors.unit}</p>
                    )}
                  </div>
                </div>

                <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4'>
                  <div className='space-y-1'>
                    <Label htmlFor='email' className='text-xs font-medium'>
                      Email Address
                    </Label>
                    <Input
                      id='email'
                      type='email'
                      placeholder='Enter email address'
                      value={formData.email}
                      onChange={(e) => handleInputChange('email', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                    {errors.email && (
                      <p className='text-destructive text-xs mt-1'>{errors.email}</p>
                    )}
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='dateOfBirth' className='text-xs font-medium'>
                      Date of Birth
                    </Label>
                    <Input
                      id='dateOfBirth'
                      type='date'
                      value={formData.dateOfBirth}
                      onChange={(e) => handleInputChange('dateOfBirth', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='gender' className='text-xs font-medium'>
                      Gender
                    </Label>
                    <Select
                      value={formData.gender}
                      onValueChange={(value) => handleSelectChange('gender', value)}
                    >
                      <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'>
                        <SelectValue placeholder='Select gender' />
                      </SelectTrigger>
                      <SelectContent>
                        {/* TODO: Populate from API */}
                        {genders.map((gender) => (
                          <SelectItem key={gender.value} value={gender.value}>
                            {gender.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='maritalStatus' className='text-xs font-medium'>
                      Marital Status
                    </Label>
                    <Select
                      value={formData.maritalStatus}
                      onValueChange={(value) => handleSelectChange('maritalStatus', value)}
                    >
                      <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'>
                        <SelectValue placeholder='Select status' />
                      </SelectTrigger>
                      <SelectContent>
                        {/* TODO: Populate from API */}
                        {maritalStatuses.map((status) => (
                          <SelectItem key={status.value} value={status.value}>
                            {status.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>

              {/* Address Information */}
              <div className='space-y-2'>
               

                <div className='space-y-1'>
                  <Label htmlFor='address' className='text-xs font-medium'>
                    Address
                  </Label>
                  <Textarea
                    id='address'
                    placeholder='Enter full address'
                    value={formData.address}
                    onChange={(e) => handleInputChange('address', e.target.value)}
                    className='min-h-[40px] px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs resize-none transition-all duration-200'
                  />
                </div>

                <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4'>
                  <div className='space-y-1'>
                    <Label htmlFor='city' className='text-xs font-medium'>
                      City
                    </Label>
                    <Input
                      id='city'
                      placeholder='Enter city'
                      value={formData.city}
                      onChange={(e) => handleInputChange('city', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='state' className='text-xs font-medium'>
                      State/Province
                    </Label>
                    <Input
                      id='state'
                      placeholder='Enter state'
                      value={formData.state}
                      onChange={(e) => handleInputChange('state', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='postalCode' className='text-xs font-medium'>
                      Postal Code
                    </Label>
                    <Input
                      id='postalCode'
                      placeholder='Enter postal code'
                      value={formData.postalCode}
                      onChange={(e) => handleInputChange('postalCode', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='country' className='text-xs font-medium'>
                      Country
                    </Label>
                    <Input
                      id='country'
                      placeholder='Enter country'
                      value={formData.country}
                      onChange={(e) => handleInputChange('country', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                  </div>
                </div>
              </div>


              {/* Employment Information */}
              <div className='space-y-2'>
                <h4 className='text-xs font-medium text-muted-foreground border-b pb-1'>
                  Employment Information
                </h4>

                <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-6 gap-4'>
                  <div className='space-y-1'>
                    <Label htmlFor='employeeId' className='text-xs font-medium'>
                      Employee ID
                    </Label>
                    <div className='h-8 px-2 py-1 bg-muted/30 rounded-[5px] text-xs flex items-center border border-input'>
                      {editingEmployee && formData.employeeId 
                        ? formData.employeeId 
                        : editingEmployee 
                        ? 'Loading...' 
                        : 'Will be assigned by system'}
                    </div>
                  </div>

                  <div className={`space-y-1 ${showCustomDepartmentInput ? 'lg:col-span-2 md:col-span-2' : ''}`}>
                    <Label htmlFor='department' className='text-xs font-medium'>
                      Department
                    </Label>
                    <Select
                      value={formData.department}
                      onValueChange={(value) => handleSelectChange('department', value)}
                    >
                      <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'>
                        <SelectValue placeholder='Select department' />
                      </SelectTrigger>
                      <SelectContent>
                        {isLoadingDepartments ? (
                          <SelectItem value="loading" disabled>
                            Loading departments...
                          </SelectItem>
                        ) : (
                          <>
                        {departments.map((dept) => (
                              <SelectItem key={dept.id} value={dept.name}>
                                {dept.name}
                          </SelectItem>
                        ))}
                            <SelectItem value='Add Department'>Add New Department</SelectItem>
                          </>
                        )}
                      </SelectContent>
                    </Select>
                    {errors.department && (
                      <p className='text-destructive text-xs mt-1'>{errors.department}</p>
                    )}
                    
                    {/* Custom Department Input */}
                    {showCustomDepartmentInput && (
                      <div className='p-3 rounded-lg space-y-2 mt-2 w-full bg-background border border-input shadow-lg relative z-50'>
                        <Label className='text-xs font-medium text-blue-800'>
                          Add New Department
                        </Label>
                        <div className='flex flex-col sm:flex-row gap-2'>
                          <Input
                            placeholder='Enter department name'
                            value={customDepartment}
                            onChange={(e) => {
                              setCustomDepartment(e.target.value);
                              if (errors.customDepartment) {
                                setErrors((prev) => ({ ...prev, customDepartment: '' }));
                              }
                            }}
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') {
                                e.preventDefault();
                                handleAddDepartment();
                              }
                            }}
                            className='flex-1 min-w-0 sm:min-w-[200px] h-8 px-3 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                          />
                          <div className='flex gap-2'>
                            <Button
                              type='button'
                              onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                handleAddDepartment();
                              }}
                              variant='default'
                              size='sm'
                              className='h-8 px-3 flex-1 sm:flex-initial relative z-50'
                              disabled={isLoadingDepartments}
                            >
                              {isLoadingDepartments ? (
                                <>
                                  <Loader2 className='w-3 h-3 mr-1 animate-spin' />
                                  Adding...
                                </>
                              ) : (
                                'Add'
                              )}
                            </Button>
                            <Button
                              type='button'
                              onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                setShowCustomDepartmentInput(false);
                                setCustomDepartment('');
                                setFormData(prev => ({ ...prev, department: '' }));
                                setErrors((prev) => ({ ...prev, customDepartment: '' }));
                              }}
                              variant='outline'
                              size='sm'
                              className='h-8 px-3 relative z-10'
                            >
                              <X className='w-3 h-3' />
                            </Button>
                          </div>
                        </div>
                        {errors.customDepartment && (
                          <p className='text-destructive text-xs mt-1'>{errors.customDepartment}</p>
                        )}
                      </div>
                    )}
                  </div>

                  <div className={`space-y-1 ${showCustomPositionInput ? 'lg:col-span-2 md:col-span-2' : ''}`}>
                    <Label htmlFor='position' className='text-xs font-medium'>
                      Position/Job Title
                    </Label>
                    <Select
                      value={formData.position}
                      onValueChange={(value) => handleSelectChange('position', value)}
                    >
                      <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'>
                        <SelectValue placeholder='Select position' />
                      </SelectTrigger>
                      <SelectContent>
                        {isLoadingPositions ? (
                          <SelectItem value="loading" disabled>
                            Loading positions...
                          </SelectItem>
                        ) : (
                          <>
                            {positions.map((pos) => (
                              <SelectItem key={pos.id} value={pos.name} className='text-left'>
                                {pos.name}
                              </SelectItem>
                            ))}
                            <SelectItem value='Add Position'>Add New Position</SelectItem>
                          </>
                        )}
                      </SelectContent>
                    </Select>
                    {errors.position && (
                      <p className='text-destructive text-xs mt-1'>{errors.position}</p>
                    )}
                    
                    {/* Custom Position Input */}
                    {showCustomPositionInput && (
                      <div className='p-3 rounded-lg space-y-2 mt-2 w-full bg-background border border-input shadow-lg relative z-50'>
                        <Label className='text-xs font-medium text-blue-800'>
                          Add New Position
                        </Label>
                        <div className='flex flex-col sm:flex-row gap-2'>
                          <Input
                            placeholder='Enter position name'
                            value={customPosition}
                            onChange={(e) => {
                              setCustomPosition(e.target.value);
                              if (errors.customPosition) {
                                setErrors((prev) => ({ ...prev, customPosition: '' }));
                              }
                            }}
                            onKeyDown={(e) => {
                              if (e.key === 'Enter') {
                                e.preventDefault();
                                handleAddPosition();
                              }
                            }}
                            className='flex-1 min-w-0 sm:min-w-[200px] h-8 px-3 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                          />
                          <div className='flex gap-2'>
                            <Button
                              type='button'
                              onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                handleAddPosition();
                              }}
                              variant='default'
                              size='sm'
                              className='h-8 px-3 flex-1 sm:flex-initial relative z-50'
                              disabled={isLoadingPositions}
                            >
                              {isLoadingPositions ? (
                                <>
                                  <Loader2 className='w-3 h-3 mr-1 animate-spin' />
                                  Adding...
                                </>
                              ) : (
                                'Add'
                              )}
                            </Button>
                            <Button
                              type='button'
                              onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                setShowCustomPositionInput(false);
                                setCustomPosition('');
                                setFormData(prev => ({ ...prev, position: '' }));
                                setErrors((prev) => ({ ...prev, customPosition: '' }));
                              }}
                              variant='outline'
                              size='sm'
                              className='h-8 px-3 relative z-10'
                            >
                              <X className='w-3 h-3' />
                            </Button>
                          </div>
                        </div>
                        {errors.customPosition && (
                          <p className='text-destructive text-xs mt-1'>{errors.customPosition}</p>
                        )}
                      </div>
                    )}
                  </div>

                  <div className='space-y-1'>
                    <Label htmlFor='joiningDate' className='text-xs font-medium'>
                      Joining Date
                    </Label>
                    <Input
                      id='joiningDate'
                      type='date'
                      value={formData.joiningDate}
                      onChange={(e) => handleInputChange('joiningDate', e.target.value)}
                      className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'
                    />
                    {errors.joiningDate && (
                      <p className='text-destructive text-xs mt-1'>{errors.joiningDate}</p>
                    )}
                  </div>

                  {editingEmployee && (
                    <div className='space-y-1'>
                      <Label htmlFor='terminated' className='text-xs font-medium'>
                        Terminated
                      </Label>
                      <Select
                        value={formData.terminated}
                        onValueChange={(value) => handleSelectChange('terminated', value)}
                      >
                        <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'>
                          <SelectValue placeholder='Select status' />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value='no'>No</SelectItem>
                          <SelectItem value='yes'>Yes</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  )}

                  <div className='space-y-1'>
                    <Label htmlFor='contractType' className='text-xs font-medium'>
                      Employment Type
                    </Label>
                    <Select
                      value={formData.contractType}
                      onValueChange={(value) => handleSelectChange('contractType', value)}
                    >
                      <SelectTrigger className='h-8 px-2 py-1 border border-input bg-background hover:border-primary/50 focus:border-transparent focus:ring-0 outline-none rounded-[5px] text-xs transition-all duration-200'>
                        <SelectValue placeholder='Select employment type' />
                      </SelectTrigger>
                      <SelectContent>
                        {contractTypes.map((contract) => (
                          <SelectItem key={contract.value} value={contract.value} className='text-left'>
                            {contract.label}
                          </SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                    {errors.contractType && (
                      <p className='text-destructive text-xs mt-1'>{errors.contractType}</p>
                    )}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Form Actions */}
          <div className='flex justify-end gap-3 pt-4 border-t'>
            <Button
              type='button'
              variant='outline'
              onClick={handleClose}
              className='h-8 px-4'
            >
              <X className='w-3 h-3 mr-1' />
              Cancel
            </Button>
            <Button
              type='submit'
              className='h-8 px-4 bg-primary hover:bg-primary/90'
              disabled={isSubmitting}
            >
              {isSubmitting ? (
                <>
                  <Loader2 className='w-3 h-3 mr-1 animate-spin' />
                  Submitting...
                </>
              ) : (
                <>
                  Submit
                </>
              )}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};
